### ISSUE TITLE
Getting GraphQLError: Syntax Error: Cannot parse the unexpected character

### ISSUE THREAD

**Issue by netpoe** [dangcuuson/graphql-schema-typescript#41]
When running `graphql-schema-typescript generate-ts ./src/datamodel/testSchema.graphql --output ./src/datamodel/testSchema.d.ts` from my package.json script: 
```
"generate:schema": "graphql-schema-typescript generate-ts ./src/datamodel/testSchema.graphql --output ./src/datamodel/testSchema.d.ts"
```

I get the following error: 

```
$ graphql-schema-typescript generate-ts ./src/datamodel/testSchema.graphql --output ./src/datamodel/testSchema.d.ts
Message:  null
Error:  GraphQLError: Syntax Error: Cannot parse the unexpected character ".".
    at syntaxError (/root/ziina/monorepo/graphqlserver/node_modules/graphql/error/syntaxError.js:15:10)
    at readToken (/root/ziina/monorepo/graphqlserver/node_modules/graphql/language/lexer.js:270:38)
    at Object.lookahead (/root/ziina/monorepo/graphqlserver/node_modules/graphql/language/lexer.js:54:43)
    at Object.advanceLexer [as advance] (/root/ziina/monorepo/graphqlserver/node_modules/graphql/language/lexer.js:44:33)
    at Parser.expectToken (/root/ziina/monorepo/graphqlserver/node_modules/graphql/language/parser.js:1399:19)
    at Parser.many (/root/ziina/monorepo/graphqlserver/node_modules/graphql/language/parser.js:1514:10)
    at Parser.parseDocument (/root/ziina/monorepo/graphqlserver/node_modules/graphql/language/parser.js:111:25)
    at parse (/root/ziina/monorepo/graphqlserver/node_modules/graphql/language/parser.js:36:17)
    at Object.buildSchema (/root/ziina/monorepo/graphqlserver/node_modules/graphql/utilities/buildASTSchema.js:462:43)
    at Object.<anonymous> (/root/ziina/monorepo/graphqlserver/node_modules/graphql-schema-typescript/lib/index.js:94:42) {
  message: 'Syntax Error: Cannot parse the unexpected character ".".',
  locations: [ { line: 1, column: 1 } ]
}
error Command failed with exit code 1.
```

I've tried with escaping double quotes, single quotes, etc.
I've also tried to use the `testSchema.graphql` from the `__tests__`  to no avail.

Seems like a parse issue with the directory paths?

**Comment by netpoe** [comment]
@dangcuuson ?

**Comment by QuestionAndAnswer** [comment]
Has the same issue after adding ```union FullWidget = Widget | JSON```

**Comment by netpoe** [comment]
> Has the same issue after adding `union FullWidget = Widget | JSON`

@QuestionAndAnswer in my case, I ended up using: https://www.npmjs.com/package/@graphql-codegen/typescript-resolvers instead of this.

**Comment by nathanbirrell** [comment]
This is still an issue BTW
